set MATLAB=C:\Program Files (x86)\MATLAB\R2014b
make -f my_pv_system_3_ss_calculation.mk  EXT_MODE=0 EXTMODE_STATIC_ALLOC=0 TMW_EXTMODE_TESTING=0 EXTMODE_STATIC_ALLOC_SIZE=1000000 EXTMODE_TRANSPORT=0
