set MATLAB=C:\Program Files (x86)\MATLAB\R2014b
make -f boost_and_two_level__1_sm_ehs.mk  EXT_MODE=0 EXTMODE_STATIC_ALLOC=0 TMW_EXTMODE_TESTING=0 EXTMODE_STATIC_ALLOC_SIZE=1000000 EXTMODE_TRANSPORT=0
