/**
 * This function is generated by RT-LAB during model compilation (at 'generation' step).
 * This function copies data from src to dst, ignoring pointers.
 * Note that only PWork are supposed to be pointers within a DWork structure
 * and that sub-structures are copied in one operation since they do not contain pointers.
 */
int OpalSnapshot_Copy_DWork(void * src, void * dst) {
   D_Work * pSrc = (D_Work*)src;
   D_Work * pDst = (D_Work*)dst;
   int size = 0, eltSize = 0;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE);
   memcpy(&pDst->UnitDelay_DSTATE, &pSrc->UnitDelay_DSTATE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_b);
   memcpy(&pDst->UnitDelay_DSTATE_b, &pSrc->UnitDelay_DSTATE_b, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->DiscreteTimeIntegrator_DSTATE);
   memcpy(&pDst->DiscreteTimeIntegrator_DSTATE, &pSrc->DiscreteTimeIntegrator_DSTATE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Delay_x1_DSTATE);
   memcpy(&pDst->Delay_x1_DSTATE, &pSrc->Delay_x1_DSTATE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Delay_x2_DSTATE);
   memcpy(&pDst->Delay_x2_DSTATE, &pSrc->Delay_x2_DSTATE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay2_DSTATE);
   memcpy(&pDst->UnitDelay2_DSTATE, &pSrc->UnitDelay2_DSTATE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integrator_DSTATE);
   memcpy(&pDst->Integrator_DSTATE, &pSrc->Integrator_DSTATE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE);
   memcpy(&pDst->Integ4_DSTATE, &pSrc->Integ4_DSTATE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_d);
   memcpy(&pDst->UnitDelay_DSTATE_d, &pSrc->UnitDelay_DSTATE_d, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay1_DSTATE);
   memcpy(&pDst->UnitDelay1_DSTATE, &pSrc->UnitDelay1_DSTATE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_f);
   memcpy(&pDst->Integ4_DSTATE_f, &pSrc->Integ4_DSTATE_f, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_i);
   memcpy(&pDst->UnitDelay_DSTATE_i, &pSrc->UnitDelay_DSTATE_i, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay1_DSTATE_i);
   memcpy(&pDst->UnitDelay1_DSTATE_i, &pSrc->UnitDelay1_DSTATE_i, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_g);
   memcpy(&pDst->Integ4_DSTATE_g, &pSrc->Integ4_DSTATE_g, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_h);
   memcpy(&pDst->UnitDelay_DSTATE_h, &pSrc->UnitDelay_DSTATE_h, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay1_DSTATE_im);
   memcpy(&pDst->UnitDelay1_DSTATE_im, &pSrc->UnitDelay1_DSTATE_im, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_k);
   memcpy(&pDst->Integ4_DSTATE_k, &pSrc->Integ4_DSTATE_k, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_f);
   memcpy(&pDst->UnitDelay_DSTATE_f, &pSrc->UnitDelay_DSTATE_f, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay1_DSTATE_e);
   memcpy(&pDst->UnitDelay1_DSTATE_e, &pSrc->UnitDelay1_DSTATE_e, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->DiscreteDerivative_states);
   memcpy(&pDst->DiscreteDerivative_states, &pSrc->DiscreteDerivative_states, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->DiscreteTimeIntegrator_DSTATE_o);
   memcpy(&pDst->DiscreteTimeIntegrator_DSTATE_o, &pSrc->DiscreteTimeIntegrator_DSTATE_o, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Delay_x1_DSTATE_p);
   memcpy(&pDst->Delay_x1_DSTATE_p, &pSrc->Delay_x1_DSTATE_p, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Delay_x2_DSTATE_l);
   memcpy(&pDst->Delay_x2_DSTATE_l, &pSrc->Delay_x2_DSTATE_l, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay3_DSTATE);
   memcpy(&pDst->UnitDelay3_DSTATE, &pSrc->UnitDelay3_DSTATE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay1_DSTATE_n);
   memcpy(&pDst->UnitDelay1_DSTATE_n, &pSrc->UnitDelay1_DSTATE_n, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integrator_DSTATE_h);
   memcpy(&pDst->Integrator_DSTATE_h, &pSrc->Integrator_DSTATE_h, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_i);
   memcpy(&pDst->Integ4_DSTATE_i, &pSrc->Integ4_DSTATE_i, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_c);
   memcpy(&pDst->UnitDelay_DSTATE_c, &pSrc->UnitDelay_DSTATE_c, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay1_DSTATE_eb);
   memcpy(&pDst->UnitDelay1_DSTATE_eb, &pSrc->UnitDelay1_DSTATE_eb, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_c);
   memcpy(&pDst->Integ4_DSTATE_c, &pSrc->Integ4_DSTATE_c, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_fv);
   memcpy(&pDst->UnitDelay_DSTATE_fv, &pSrc->UnitDelay_DSTATE_fv, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay1_DSTATE_k);
   memcpy(&pDst->UnitDelay1_DSTATE_k, &pSrc->UnitDelay1_DSTATE_k, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_PreviousInput);
   memcpy(&pDst->SFunction_PreviousInput, &pSrc->SFunction_PreviousInput, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory1_1_PreviousInput);
   memcpy(&pDst->Memory1_1_PreviousInput, &pSrc->Memory1_1_PreviousInput, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory1_2_PreviousInput);
   memcpy(&pDst->Memory1_2_PreviousInput, &pSrc->Memory1_2_PreviousInput, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory1_3_PreviousInput);
   memcpy(&pDst->Memory1_3_PreviousInput, &pSrc->Memory1_3_PreviousInput, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory1_4_PreviousInput);
   memcpy(&pDst->Memory1_4_PreviousInput, &pSrc->Memory1_4_PreviousInput, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory1_PreviousInput);
   memcpy(&pDst->Memory1_PreviousInput, &pSrc->Memory1_PreviousInput, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory_PreviousInput);
   memcpy(&pDst->Memory_PreviousInput, &pSrc->Memory_PreviousInput, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory2_1_PreviousInput);
   memcpy(&pDst->Memory2_1_PreviousInput, &pSrc->Memory2_1_PreviousInput, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory2_2_PreviousInput);
   memcpy(&pDst->Memory2_2_PreviousInput, &pSrc->Memory2_2_PreviousInput, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory2_3_PreviousInput);
   memcpy(&pDst->Memory2_3_PreviousInput, &pSrc->Memory2_3_PreviousInput, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory_1_PreviousInput);
   memcpy(&pDst->Memory_1_PreviousInput, &pSrc->Memory_1_PreviousInput, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory_2_PreviousInput);
   memcpy(&pDst->Memory_2_PreviousInput, &pSrc->Memory_2_PreviousInput, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory_3_PreviousInput);
   memcpy(&pDst->Memory_3_PreviousInput, &pSrc->Memory_3_PreviousInput, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory_4_PreviousInput);
   memcpy(&pDst->Memory_4_PreviousInput, &pSrc->Memory_4_PreviousInput, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory_5_PreviousInput);
   memcpy(&pDst->Memory_5_PreviousInput, &pSrc->Memory_5_PreviousInput, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory_6_PreviousInput);
   memcpy(&pDst->Memory_6_PreviousInput, &pSrc->Memory_6_PreviousInput, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory3_1_PreviousInput);
   memcpy(&pDst->Memory3_1_PreviousInput, &pSrc->Memory3_1_PreviousInput, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory3_2_PreviousInput);
   memcpy(&pDst->Memory3_2_PreviousInput, &pSrc->Memory3_2_PreviousInput, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory1_PreviousInput_h);
   memcpy(&pDst->Memory1_PreviousInput_h, &pSrc->Memory1_PreviousInput_h, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory2_PreviousInput);
   memcpy(&pDst->Memory2_PreviousInput, &pSrc->Memory2_PreviousInput, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory1_PreviousInput_n);
   memcpy(&pDst->Memory1_PreviousInput_n, &pSrc->Memory1_PreviousInput_n, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory_PreviousInput_l);
   memcpy(&pDst->Memory_PreviousInput_l, &pSrc->Memory_PreviousInput_l, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory1_PreviousInput_o);
   memcpy(&pDst->Memory1_PreviousInput_o, &pSrc->Memory1_PreviousInput_o, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory_PreviousInput_h);
   memcpy(&pDst->Memory_PreviousInput_h, &pSrc->Memory_PreviousInput_h, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory_PreviousInput_n);
   memcpy(&pDst->Memory_PreviousInput_n, &pSrc->Memory_PreviousInput_n, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory_PreviousInput_e);
   memcpy(&pDst->Memory_PreviousInput_e, &pSrc->Memory_PreviousInput_e, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->DiscreteDerivative_tmp);
   memcpy(&pDst->DiscreteDerivative_tmp, &pSrc->DiscreteDerivative_tmp, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->PrevY);
   memcpy(&pDst->PrevY, &pSrc->PrevY, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Vold);
   memcpy(&pDst->Vold, &pSrc->Vold, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Pold);
   memcpy(&pDst->Pold, &pSrc->Pold, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Dold);
   memcpy(&pDst->Dold, &pSrc->Dold, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TransportDelay_RWORK);
   memcpy(&pDst->TransportDelay_RWORK, &pSrc->TransportDelay_RWORK, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TransportDelay_RWORK_o);
   memcpy(&pDst->TransportDelay_RWORK_o, &pSrc->TransportDelay_RWORK_o, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->RTEConversion_RWORK);
   memcpy(&pDst->RTEConversion_RWORK, &pSrc->RTEConversion_RWORK, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->RTEConversion1_RWORK);
   memcpy(&pDst->RTEConversion1_RWORK, &pSrc->RTEConversion1_RWORK, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_RWORK);
   memcpy(&pDst->SFunction_RWORK, &pSrc->SFunction_RWORK, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_RWORK_d);
   memcpy(&pDst->SFunction_RWORK_d, &pSrc->SFunction_RWORK_d, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_RWORK_g);
   memcpy(&pDst->SFunction_RWORK_g, &pSrc->SFunction_RWORK_g, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_RWORK_m);
   memcpy(&pDst->SFunction_RWORK_m, &pSrc->SFunction_RWORK_m, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_RWORK_m4);
   memcpy(&pDst->SFunction_RWORK_m4, &pSrc->SFunction_RWORK_m4, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_RWORK_e);
   memcpy(&pDst->SFunction_RWORK_e, &pSrc->SFunction_RWORK_e, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_RWORK_p);
   memcpy(&pDst->SFunction_RWORK_p, &pSrc->SFunction_RWORK_p, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->DelayInput1_DSTATE);
   memcpy(&pDst->DelayInput1_DSTATE, &pSrc->DelayInput1_DSTATE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->DelayInput1_DSTATE_m);
   memcpy(&pDst->DelayInput1_DSTATE_m, &pSrc->DelayInput1_DSTATE_m, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->DelayInput1_DSTATE_k);
   memcpy(&pDst->DelayInput1_DSTATE_k, &pSrc->DelayInput1_DSTATE_k, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK);
   memcpy(&pDst->SFunction_IWORK, &pSrc->SFunction_IWORK, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_b);
   memcpy(&pDst->SFunction_IWORK_b, &pSrc->SFunction_IWORK_b, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_j);
   memcpy(&pDst->SFunction_IWORK_j, &pSrc->SFunction_IWORK_j, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_o);
   memcpy(&pDst->SFunction_IWORK_o, &pSrc->SFunction_IWORK_o, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_m);
   memcpy(&pDst->SFunction_IWORK_m, &pSrc->SFunction_IWORK_m, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TransportDelay_IWORK);
   memcpy(&pDst->TransportDelay_IWORK, &pSrc->TransportDelay_IWORK, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TransportDelay_IWORK_g);
   memcpy(&pDst->TransportDelay_IWORK_g, &pSrc->TransportDelay_IWORK_g, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_n);
   memcpy(&pDst->SFunction_IWORK_n, &pSrc->SFunction_IWORK_n, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_bd);
   memcpy(&pDst->SFunction_IWORK_bd, &pSrc->SFunction_IWORK_bd, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_jw);
   memcpy(&pDst->SFunction_IWORK_jw, &pSrc->SFunction_IWORK_jw, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_os);
   memcpy(&pDst->SFunction_IWORK_os, &pSrc->SFunction_IWORK_os, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_k);
   memcpy(&pDst->SFunction_IWORK_k, &pSrc->SFunction_IWORK_k, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->OpTrigger_IWORK);
   memcpy(&pDst->OpTrigger_IWORK, &pSrc->OpTrigger_IWORK, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->OpCtrl_IWORK);
   memcpy(&pDst->OpCtrl_IWORK, &pSrc->OpCtrl_IWORK, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_nb);
   memcpy(&pDst->SFunction_IWORK_nb, &pSrc->SFunction_IWORK_nb, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_l);
   memcpy(&pDst->SFunction_IWORK_l, &pSrc->SFunction_IWORK_l, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE, &pSrc->Integ4_SYSTEM_ENABLE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_n);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_n, &pSrc->Integ4_SYSTEM_ENABLE_n, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_i);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_i, &pSrc->Integ4_SYSTEM_ENABLE_i, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_e);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_e, &pSrc->Integ4_SYSTEM_ENABLE_e, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_nz);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_nz, &pSrc->Integ4_SYSTEM_ENABLE_nz, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_d);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_d, &pSrc->Integ4_SYSTEM_ENABLE_d, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Relay1_Mode);
   memcpy(&pDst->Relay1_Mode, &pSrc->Relay1_Mode, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Vold_not_empty);
   memcpy(&pDst->Vold_not_empty, &pSrc->Vold_not_empty, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->AutomaticGainControl_MODE);
   memcpy(&pDst->AutomaticGainControl_MODE, &pSrc->AutomaticGainControl_MODE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TrueRMS_i);
   memcpy(&pDst->TrueRMS_i, &pSrc->TrueRMS_i, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->RMS_h);
   memcpy(&pDst->RMS_h, &pSrc->RMS_h, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TrueRMS);
   memcpy(&pDst->TrueRMS, &pSrc->TrueRMS, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->RMS);
   memcpy(&pDst->RMS, &pSrc->RMS, eltSize);
   size += eltSize;

   return size;
}

/**
 * This function is generated by RT-LAB during model compilation (at 'generation' step).
 * This function copies data from a raw buffer (src) 
 * to an RT_MODEL structure(dst), ignoring pointers.
 * Note that sub-structures are copied in one operation since they cannot contain pointers.
 */
int OpalSnapshot_Copy_TimingData(void * src, void * dst) {
   RT_MODEL	tmpBuffer;
   RT_MODEL * pSrc = &tmpBuffer;
   RT_MODEL * pDst = (RT_MODEL *)dst;
   int TimingSize = sizeof(tmpBuffer.Timing);
   int size = 0, eltSize = 0;

   memcpy(&tmpBuffer.Timing, src, TimingSize);

   eltSize = sizeof(pSrc->Timing.clockTick0);
   memcpy(&pDst->Timing.clockTick0, &pSrc->Timing.clockTick0, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.clockTick1);
   memcpy(&pDst->Timing.clockTick1, &pSrc->Timing.clockTick1, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.clockTickH0);
   memcpy(&pDst->Timing.clockTickH0, &pSrc->Timing.clockTickH0, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.clockTickH1);
   memcpy(&pDst->Timing.clockTickH1, &pSrc->Timing.clockTickH1, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.tFinal);
   memcpy(&pDst->Timing.tFinal, &pSrc->Timing.tFinal, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.offsetTimesArray);
   memcpy(&pDst->Timing.offsetTimesArray, &pSrc->Timing.offsetTimesArray, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.perTaskSampleHitsArray);
   memcpy(&pDst->Timing.perTaskSampleHitsArray, &pSrc->Timing.perTaskSampleHitsArray, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.sampleHitArray);
   memcpy(&pDst->Timing.sampleHitArray, &pSrc->Timing.sampleHitArray, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.sampleTimesArray);
   memcpy(&pDst->Timing.sampleTimesArray, &pSrc->Timing.sampleTimesArray, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.sampleTimeTaskIDArray);
   memcpy(&pDst->Timing.sampleTimeTaskIDArray, &pSrc->Timing.sampleTimeTaskIDArray, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.simTimeStep);
   memcpy(&pDst->Timing.simTimeStep, &pSrc->Timing.simTimeStep, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.tStart);
   memcpy(&pDst->Timing.tStart, &pSrc->Timing.tStart, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.stepSize);
   memcpy(&pDst->Timing.stepSize, &pSrc->Timing.stepSize, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.stepSize0);
   memcpy(&pDst->Timing.stepSize0, &pSrc->Timing.stepSize0, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.stepSize1);
   memcpy(&pDst->Timing.stepSize1, &pSrc->Timing.stepSize1, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.stopRequestedFlag);
   memcpy(&pDst->Timing.stopRequestedFlag, &pSrc->Timing.stopRequestedFlag, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.tArray);
   memcpy(&pDst->Timing.tArray, &pSrc->Timing.tArray, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.timeOfLastOutput);
   memcpy(&pDst->Timing.timeOfLastOutput, &pSrc->Timing.timeOfLastOutput, eltSize);
   size += eltSize;

   return size;
}

/**
 * This function is generated by RT-LAB during model compilation (at 'generation' step).
 * This function copies data from a raw buffer (src) 
 * to an RT_MODEL structure(dst), ignoring pointers.
 * Note that ingData must not be copied since it contains pointers.
 */
int OpalSnapshot_Copy_ModelData(void * src, void * dst) {
   RT_MODEL	tmpBuffer;
   RT_MODEL * pSrc = &tmpBuffer;
   RT_MODEL * pDst = (RT_MODEL *)dst;
   int ModelDataSize = sizeof(tmpBuffer.ModelData);
   int size = 0, eltSize = 0;

   memcpy(&tmpBuffer.ModelData, src, ModelDataSize);

   eltSize = sizeof(pSrc->ModelData.blkStateChange);
   memcpy(&pDst->ModelData.blkStateChange, &pSrc->ModelData.blkStateChange, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->ModelData.derivCacheNeedsReset);
   memcpy(&pDst->ModelData.derivCacheNeedsReset, &pSrc->ModelData.derivCacheNeedsReset, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->ModelData.odeF);
   memcpy(&pDst->ModelData.odeF, &pSrc->ModelData.odeF, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->ModelData.odeY);
   memcpy(&pDst->ModelData.odeY, &pSrc->ModelData.odeY, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->ModelData.zCCacheNeedsReset);
   memcpy(&pDst->ModelData.zCCacheNeedsReset, &pSrc->ModelData.zCCacheNeedsReset, eltSize);
   size += eltSize;

   return size;
}

