/**
 * This function is generated by RT-LAB during model compilation (at 'generation' step).
 * This function copies data from src to dst, ignoring pointers.
 * Note that only PWork are supposed to be pointers within a DWork structure
 * and that sub-structures are copied in one operation since they do not contain pointers.
 */
int OpalSnapshot_Copy_DWork(void * src, void * dst) {
   D_Work * pSrc = (D_Work*)src;
   D_Work * pDst = (D_Work*)dst;
   int size = 0, eltSize = 0;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE);
   memcpy(&pDst->UnitDelay_DSTATE, &pSrc->UnitDelay_DSTATE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->DiscreteTimeIntegrator_DSTATE);
   memcpy(&pDst->DiscreteTimeIntegrator_DSTATE, &pSrc->DiscreteTimeIntegrator_DSTATE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Delay_x1_DSTATE);
   memcpy(&pDst->Delay_x1_DSTATE, &pSrc->Delay_x1_DSTATE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Delay_x2_DSTATE);
   memcpy(&pDst->Delay_x2_DSTATE, &pSrc->Delay_x2_DSTATE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay2_DSTATE);
   memcpy(&pDst->UnitDelay2_DSTATE, &pSrc->UnitDelay2_DSTATE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integrator_DSTATE);
   memcpy(&pDst->Integrator_DSTATE, &pSrc->Integrator_DSTATE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE);
   memcpy(&pDst->Integ4_DSTATE, &pSrc->Integ4_DSTATE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_g);
   memcpy(&pDst->UnitDelay_DSTATE_g, &pSrc->UnitDelay_DSTATE_g, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay1_DSTATE);
   memcpy(&pDst->UnitDelay1_DSTATE, &pSrc->UnitDelay1_DSTATE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_d);
   memcpy(&pDst->Integ4_DSTATE_d, &pSrc->Integ4_DSTATE_d, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_i);
   memcpy(&pDst->UnitDelay_DSTATE_i, &pSrc->UnitDelay_DSTATE_i, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay1_DSTATE_b);
   memcpy(&pDst->UnitDelay1_DSTATE_b, &pSrc->UnitDelay1_DSTATE_b, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_d5);
   memcpy(&pDst->Integ4_DSTATE_d5, &pSrc->Integ4_DSTATE_d5, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_iq);
   memcpy(&pDst->UnitDelay_DSTATE_iq, &pSrc->UnitDelay_DSTATE_iq, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay1_DSTATE_a);
   memcpy(&pDst->UnitDelay1_DSTATE_a, &pSrc->UnitDelay1_DSTATE_a, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_k);
   memcpy(&pDst->Integ4_DSTATE_k, &pSrc->Integ4_DSTATE_k, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_a);
   memcpy(&pDst->UnitDelay_DSTATE_a, &pSrc->UnitDelay_DSTATE_a, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay1_DSTATE_i);
   memcpy(&pDst->UnitDelay1_DSTATE_i, &pSrc->UnitDelay1_DSTATE_i, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->DiscreteDerivative_states);
   memcpy(&pDst->DiscreteDerivative_states, &pSrc->DiscreteDerivative_states, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->DiscreteTimeIntegrator_DSTATE_d);
   memcpy(&pDst->DiscreteTimeIntegrator_DSTATE_d, &pSrc->DiscreteTimeIntegrator_DSTATE_d, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Delay_x1_DSTATE_d);
   memcpy(&pDst->Delay_x1_DSTATE_d, &pSrc->Delay_x1_DSTATE_d, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Delay_x2_DSTATE_m);
   memcpy(&pDst->Delay_x2_DSTATE_m, &pSrc->Delay_x2_DSTATE_m, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_il);
   memcpy(&pDst->UnitDelay_DSTATE_il, &pSrc->UnitDelay_DSTATE_il, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay3_DSTATE);
   memcpy(&pDst->UnitDelay3_DSTATE, &pSrc->UnitDelay3_DSTATE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay1_DSTATE_e);
   memcpy(&pDst->UnitDelay1_DSTATE_e, &pSrc->UnitDelay1_DSTATE_e, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integrator_DSTATE_d);
   memcpy(&pDst->Integrator_DSTATE_d, &pSrc->Integrator_DSTATE_d, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_ky);
   memcpy(&pDst->Integ4_DSTATE_ky, &pSrc->Integ4_DSTATE_ky, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_l);
   memcpy(&pDst->UnitDelay_DSTATE_l, &pSrc->UnitDelay_DSTATE_l, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay1_DSTATE_o);
   memcpy(&pDst->UnitDelay1_DSTATE_o, &pSrc->UnitDelay1_DSTATE_o, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_j);
   memcpy(&pDst->Integ4_DSTATE_j, &pSrc->Integ4_DSTATE_j, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_d);
   memcpy(&pDst->UnitDelay_DSTATE_d, &pSrc->UnitDelay_DSTATE_d, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay1_DSTATE_k);
   memcpy(&pDst->UnitDelay1_DSTATE_k, &pSrc->UnitDelay1_DSTATE_k, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_PreviousInput);
   memcpy(&pDst->SFunction_PreviousInput, &pSrc->SFunction_PreviousInput, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory_PreviousInput);
   memcpy(&pDst->Memory_PreviousInput, &pSrc->Memory_PreviousInput, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->DiscreteDerivative_tmp);
   memcpy(&pDst->DiscreteDerivative_tmp, &pSrc->DiscreteDerivative_tmp, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->PrevY);
   memcpy(&pDst->PrevY, &pSrc->PrevY, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Vold);
   memcpy(&pDst->Vold, &pSrc->Vold, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Pold);
   memcpy(&pDst->Pold, &pSrc->Pold, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Dold);
   memcpy(&pDst->Dold, &pSrc->Dold, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_RWORK);
   memcpy(&pDst->SFunction_RWORK, &pSrc->SFunction_RWORK, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_RWORK_a);
   memcpy(&pDst->SFunction_RWORK_a, &pSrc->SFunction_RWORK_a, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_RWORK_o);
   memcpy(&pDst->SFunction_RWORK_o, &pSrc->SFunction_RWORK_o, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_RWORK_k);
   memcpy(&pDst->SFunction_RWORK_k, &pSrc->SFunction_RWORK_k, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_RWORK_j);
   memcpy(&pDst->SFunction_RWORK_j, &pSrc->SFunction_RWORK_j, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_RWORK_kx);
   memcpy(&pDst->SFunction_RWORK_kx, &pSrc->SFunction_RWORK_kx, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_RWORK_m);
   memcpy(&pDst->SFunction_RWORK_m, &pSrc->SFunction_RWORK_m, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK);
   memcpy(&pDst->SFunction_IWORK, &pSrc->SFunction_IWORK, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_f);
   memcpy(&pDst->SFunction_IWORK_f, &pSrc->SFunction_IWORK_f, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_p);
   memcpy(&pDst->SFunction_IWORK_p, &pSrc->SFunction_IWORK_p, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_b);
   memcpy(&pDst->SFunction_IWORK_b, &pSrc->SFunction_IWORK_b, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_c);
   memcpy(&pDst->SFunction_IWORK_c, &pSrc->SFunction_IWORK_c, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_bf);
   memcpy(&pDst->SFunction_IWORK_bf, &pSrc->SFunction_IWORK_bf, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_pd);
   memcpy(&pDst->SFunction_IWORK_pd, &pSrc->SFunction_IWORK_pd, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_c4);
   memcpy(&pDst->SFunction_IWORK_c4, &pSrc->SFunction_IWORK_c4, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE, &pSrc->Integ4_SYSTEM_ENABLE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_e);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_e, &pSrc->Integ4_SYSTEM_ENABLE_e, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_d);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_d, &pSrc->Integ4_SYSTEM_ENABLE_d, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_k);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_k, &pSrc->Integ4_SYSTEM_ENABLE_k, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_g);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_g, &pSrc->Integ4_SYSTEM_ENABLE_g, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_gx);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_gx, &pSrc->Integ4_SYSTEM_ENABLE_gx, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Vold_not_empty);
   memcpy(&pDst->Vold_not_empty, &pSrc->Vold_not_empty, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->AutomaticGainControl_MODE);
   memcpy(&pDst->AutomaticGainControl_MODE, &pSrc->AutomaticGainControl_MODE, eltSize);
   size += eltSize;

   return size;
}

/**
 * This function is generated by RT-LAB during model compilation (at 'generation' step).
 * This function copies data from a raw buffer (src) 
 * to an RT_MODEL structure(dst), ignoring pointers.
 * Note that sub-structures are copied in one operation since they cannot contain pointers.
 */
int OpalSnapshot_Copy_TimingData(void * src, void * dst) {
   RT_MODEL	tmpBuffer;
   RT_MODEL * pSrc = &tmpBuffer;
   RT_MODEL * pDst = (RT_MODEL *)dst;
   int TimingSize = sizeof(tmpBuffer.Timing);
   int size = 0, eltSize = 0;

   memcpy(&tmpBuffer.Timing, src, TimingSize);

   eltSize = sizeof(pSrc->Timing.clockTick0);
   memcpy(&pDst->Timing.clockTick0, &pSrc->Timing.clockTick0, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.clockTickH0);
   memcpy(&pDst->Timing.clockTickH0, &pSrc->Timing.clockTickH0, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.tFinal);
   memcpy(&pDst->Timing.tFinal, &pSrc->Timing.tFinal, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.offsetTimesArray);
   memcpy(&pDst->Timing.offsetTimesArray, &pSrc->Timing.offsetTimesArray, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.perTaskSampleHitsArray);
   memcpy(&pDst->Timing.perTaskSampleHitsArray, &pSrc->Timing.perTaskSampleHitsArray, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.sampleHitArray);
   memcpy(&pDst->Timing.sampleHitArray, &pSrc->Timing.sampleHitArray, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.sampleTimesArray);
   memcpy(&pDst->Timing.sampleTimesArray, &pSrc->Timing.sampleTimesArray, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.sampleTimeTaskIDArray);
   memcpy(&pDst->Timing.sampleTimeTaskIDArray, &pSrc->Timing.sampleTimeTaskIDArray, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.simTimeStep);
   memcpy(&pDst->Timing.simTimeStep, &pSrc->Timing.simTimeStep, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.tStart);
   memcpy(&pDst->Timing.tStart, &pSrc->Timing.tStart, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.stepSize);
   memcpy(&pDst->Timing.stepSize, &pSrc->Timing.stepSize, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.stepSize0);
   memcpy(&pDst->Timing.stepSize0, &pSrc->Timing.stepSize0, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.stopRequestedFlag);
   memcpy(&pDst->Timing.stopRequestedFlag, &pSrc->Timing.stopRequestedFlag, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.tArray);
   memcpy(&pDst->Timing.tArray, &pSrc->Timing.tArray, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.timeOfLastOutput);
   memcpy(&pDst->Timing.timeOfLastOutput, &pSrc->Timing.timeOfLastOutput, eltSize);
   size += eltSize;

   return size;
}

/**
 * This function is generated by RT-LAB during model compilation (at 'generation' step).
 * This function copies data from a raw buffer (src) 
 * to an RT_MODEL structure(dst), ignoring pointers.
 * Note that ingData must not be copied since it contains pointers.
 */
int OpalSnapshot_Copy_ModelData(void * src, void * dst) {
   RT_MODEL	tmpBuffer;
   RT_MODEL * pSrc = &tmpBuffer;
   RT_MODEL * pDst = (RT_MODEL *)dst;
   int ModelDataSize = sizeof(tmpBuffer.ModelData);
   int size = 0, eltSize = 0;

   memcpy(&tmpBuffer.ModelData, src, ModelDataSize);

   eltSize = sizeof(pSrc->ModelData.blkStateChange);
   memcpy(&pDst->ModelData.blkStateChange, &pSrc->ModelData.blkStateChange, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->ModelData.derivCacheNeedsReset);
   memcpy(&pDst->ModelData.derivCacheNeedsReset, &pSrc->ModelData.derivCacheNeedsReset, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->ModelData.zCCacheNeedsReset);
   memcpy(&pDst->ModelData.zCCacheNeedsReset, &pSrc->ModelData.zCCacheNeedsReset, eltSize);
   size += eltSize;

   return size;
}

